=== Z-H-Sun/CDM_18/ChemDraw 18.0.app/Contents/Resources/SpecialPurpose/ChemDraw Items/hotkeys.dtd
<!ELEMENT Command EMPTY>
<!ATTLIST Command id (BONDDISPLAY | BONDORDER | CHARGE | DIALOG | LABELTEXT | FUSERING | AA1 | DNA | RNA) #REQUIRED description CDATA #REQUIRED >
<!ELEMENT Commands (Command+)>
<!ELEMENT Hotkey EMPTY>
<!ATTLIST Hotkey key CDATA #REQUIRED command (BONDDISPLAY | BONDORDER | CHARGE | DIALOG | LABELTEXT | FUSERING | AA1 | DNA | RNA) #REQUIRED value CDATA #REQUIRED description CDATA #REQUIRED >
<!ELEMENT Hotkeys (Hotkey+)>
<!ELEMENT Object (Commands, Hotkeys)>
<!ATTLIST Object type (Atom | Bond | AA1 | DNA | RNA | Generic) #REQUIRED >
<!ELEMENT Objects (Object+)>

=== Z-H-Sun/CDM_18/ChemDraw 18.0.app/Contents/Resources/SpecialPurpose/ChemDraw Items/hotkeys.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE Objects SYSTEM "hotkeys.dtd">

<Objects>

	<Object type="Atom">

		<Commands>

			<Command id="LABELTEXT" description="Sets the Label for the Atoms text"/>
			<Command id="SPROUT" description="Addition of Bonds to an Atom"/>
			<Command id="CHARGE" description="Changes the charge of an Atom"/>
			<Command id="FREE_SITE" description="Increment/Decrement Free Sites of an Atom"/>
			<Command id="UPTO_SITE" description="Increment/Decrement the UpTo number of substituents of an Atom"/>
			<Command id="EXACT_SITE" description="Increment/Decrement the number of substituents of an Atom"/>
			<Command id="ATOMNUMBER" description="Show/Hide the Atom Numbers"/>
			<Command id="ATTACHMENTPOINT" description="Sets the Value of the Attachment Point"/>

		</Commands>

		<Hotkeys>

			<Hotkey key="A" command="LABELTEXT" value="Ac" description="Atom Labeling"/>
			<Hotkey key="b" command="LABELTEXT" value="Br" description="Atom Labeling"/>
			<Hotkey key="B" command="LABELTEXT" value="B" description="Atom Labeling"/>
			<Hotkey key="c" command="LABELTEXT" value="C" description="Atom Labeling"/>
			<Hotkey key="C" command="LABELTEXT" value="Cl" description="Atom Labeling"/>
			<Hotkey key="d" command="LABELTEXT" value="D" description="Atom Labeling"/>
			<Hotkey key="e" command="LABELTEXT" value="Et" description="Atom Labeling"/>
			<Hotkey key="E" command="LABELTEXT" value="COOCH3" description="Atom Labeling"/>
			<Hotkey key="f" command="LABELTEXT" value="F" description="Atom Labeling"/>
			<Hotkey key="h" command="LABELTEXT" value="H" description="Atom Labeling"/>
			<Hotkey key="i" command="LABELTEXT" value="I" description="Atom Labeling"/>
			<Hotkey key="k" command="LABELTEXT" value="K" description="Atom Labeling"/>
			<Hotkey key="l" command="LABELTEXT" value="Cl" description="Atom Labeling"/>
			<Hotkey key="m" command="LABELTEXT" value="Me" description="Atom Labeling"/>
			<Hotkey key="n" command="LABELTEXT" value="N" description="Atom Labeling"/>
			<Hotkey key="w" command="LABELTEXT" value="N" description="Atom Labeling"/>
			<Hotkey key="N" command="LABELTEXT" value="Na" description="Atom Labeling"/>
			<Hotkey key="o" command="LABELTEXT" value="O" description="Atom Labeling"/>
			<Hotkey key="q" command="LABELTEXT" value="O" description="Atom Labeling"/>
			<Hotkey key="p" command="LABELTEXT" value="P" description="Atom Labeling"/>
			<Hotkey key="P" command="LABELTEXT" value="Ph" description="Atom Labeling"/>			
			<Hotkey key="r" command="LABELTEXT" value="R" description="Atom Labeling"/>
			<Hotkey key="s" command="LABELTEXT" value="S" description="Atom Labeling"/>
			<Hotkey key="S" command="LABELTEXT" value="Si" description="Atom Labeling"/>
			<Hotkey key="x" command="LABELTEXT" value="X" description="Atom Labeling"/>						
			<Hotkey key="!" command="LABELTEXT" value="?" description="Atom Labeling"/>


			<Hotkey key="z" command="SPROUT" value="10" description="Adds an alkyne"/>
			<Hotkey key="9" command="SPROUT" value="9" description="Adds a tertiary butyl"/>
			<Hotkey key="8" command="SPROUT" value="8" description="Adds a methylidene"/>
			<Hotkey key="7" command="SPROUT" value="7" description="Adds a cyclopentane"/>
			<Hotkey key="6" command="SPROUT" value="6" description="Adds a cyclohexane"/>
			<Hotkey key="5" command="SPROUT" value="5" description="Adds a chiral down bond"/>
			<Hotkey key="4" command="SPROUT" value="4" description="Adds a chiral up bond"/>
			<Hotkey key="3" command="SPROUT" value="3" description="Adds benzene"/>
			<Hotkey key="a" command="SPROUT" value="3" description="Adds benzene"/>
			<Hotkey key="2" command="SPROUT" value="2" description="Adds carbonyl"/>
			<Hotkey key="1" command="SPROUT" value="1" description="Adds a bond to the atom in linear mode"/>
			<Hotkey key="0" command="SPROUT" value="0" description="Adds a bond to the atom in cyclic mode"/>			
			<Hotkey key=">" command="SPROUT" value="?" description="Adds bonds to the atom and new atom labels"/>

			<Hotkey key="." command="ATTACHMENTPOINT" value="True" description="Adds an attachment point"/>
			<Hotkey key="&apos;" command="ATOMNUMBER" value="True" description="Shows Atom Numbers"/>
			<Hotkey key="-" command="CHARGE" value="-" description="Decrement the charge of an atom"/>
			<Hotkey key="+" command="CHARGE" value="+" description="Increments the charge of an atom"/>

		</Hotkeys>

	</Object>

	<Object type="Bond">

		<Commands>

			<Command id="BONDORDER" description="Sets the Bond Order"/>
			<Command id="BONDDISPLAY" description="Sets the Bond Display"/>
			<Command id="BONDPOSITION" description="Sets the Position of Bonds"/>
			<Command id="BONDDOUBLEPOSITION" description="Sets the Alignment for Double Bonds"/>
			<Command id="FUSERING" description="Fuses a ring to a bond"/>

		</Commands>

		<Hotkeys>

			<Hotkey key="f" command="BONDPOSITION" value="FRONT" description="Displays the bond in the front"/>

			<Hotkey key="l" command="BONDDOUBLEPOSITION" value="LEFT" description="Align Double Bonds to the Left"/>
			<Hotkey key="r" command="BONDDOUBLEPOSITION" value="RIGHT" description="Align Double Bonds to the Right"/>
			<Hotkey key="c" command="BONDDOUBLEPOSITION" value="CENTER" description="Align Double Bonds Centered"/>

			<Hotkey key="1" command="BONDORDER" value="1" description="Set Bond to Single"/>
			<Hotkey key="2" command="BONDORDER" value="2" description="Set Bond to Double"/>
			<Hotkey key="3" command="BONDORDER" value="3" description="Set Bond to Triple"/>


			<Hotkey key="v" command="FUSERING" value="3" description="Fuse 3 membered ring"/>
			<Hotkey key="4" command="FUSERING" value="4" description="Fuse 4 membered ring"/>
			<Hotkey key="5" command="FUSERING" value="5" description="Fuse 5 membered ring"/>
			<Hotkey key="6" command="FUSERING" value="6" description="Fuse 6 membered ring"/>
			<Hotkey key="7" command="FUSERING" value="7" description="Fuse 7 membered ring"/>
			<Hotkey key="8" command="FUSERING" value="8" description="Fuse 8 membered ring"/>
			<Hotkey key="9" command="FUSERING" value="9" description="Fuse chair cyclohexane"/>
			<Hotkey key="0" command="FUSERING" value="10" description="Fuse chair cyclohexane"/>

			<Hotkey key="a" command="FUSERING" value="2" description="Fuse benzene"/>
			<Hotkey key="z" command="FUSERING" value="1" description="Fuse cyclopentadiene"/>			


			<Hotkey key="d" command="BONDDISPLAY" value="DASHED" description="Display a Bond as Dashed"/>
			<Hotkey key="H" command="BONDDISPLAY" value="HASHED" description="Display a Bond as Hashed"/>
			<Hotkey key="h" command="BONDDISPLAY" value="HASHEDWEDGED" description="Display a Bond as HashWedged"/>
			<Hotkey key="W" command="BONDDISPLAY" value="HASHEDWEDGED" description="Display a Bond as HashWedged"/>
			<Hotkey key="B" command="BONDDISPLAY" value="DOUBLEBOLD" description="Display a Bond as Bold"/>
			<Hotkey key="b" command="BONDDISPLAY" value="BOLD" description="Display a Bond as Bold"/>
			<Hotkey key="w" command="BONDDISPLAY" value="WEDGED" description="Display a Bond as Wedged"/>
			<Hotkey key="y" command="BONDDISPLAY" value="WAVY" description="Display a Bond as Wavy"/>


		</Hotkeys>

	</Object>

	<Object type="Generic">

		<Commands>

			<Command id="DIALOG" description="Display a Dialog"/>
			<Command id="TOOLMODE" description="Changes the Current Tool"/>

		</Commands>

		<Hotkeys>
			<Hotkey key="j" command="TOOLMODE" value="BENZENE" description="Activates the benzene draw tool"/>
			<Hotkey key="u" command="TOOLMODE" value="CYCLOHEXANE" description="Activates the cyclohexane draw tool"/> 
			<Hotkey key="U" command="TOOLMODE" value="CYCLOPENTANE" description="Activates the cyclopentane draw tool"/>
			<Hotkey key="J" command="TOOLMODE" value="CYCLOPENTADIENE" description="Activates the cyclopentadiene draw tool"/>
			<Hotkey key="x" command="TOOLMODE" value="SOLIDBOND" description="Activates the bond draw tool"/>                                              
			<Hotkey key="X" command="TOOLMODE" value="ACYCLICCHAIN" description="Activates the acyclic chain tool"/>
			<Hotkey key="e" command="TOOLMODE" value="ARROW" description="Activates the arrow draw tool"/>                                    
			<Hotkey key="E" command="TOOLMODE" value="CHEMICALSYMBOLS" description="Activates the drawing elements tool"/>
			<Hotkey key="t" command="TOOLMODE" value="TEXT" description="Activates the text tool"/>
			<Hotkey key="T" command="TOOLMODE" value="BRACKET" description="Activates the bracket tool"/>
			<Hotkey key="g" command="TOOLMODE" value="TLCPLATE" description="Activates the TLC plate tool"/>
			<Hotkey key="G" command="TOOLMODE" value="ORBITAL" description="Activates the orbitals tool"/>
			<Hotkey key="l" command="TOOLMODE" value="PEN" description="Activates the pen tool"/>
			<Hotkey key="L" command="TOOLMODE" value="DRAWINGELEMENTS" description="Activates the drawing tool"/>
			<Hotkey key=" " command="TOOLMODE" value="MARQUEE" description="Activates the Marquee Tool"/>
			<Hotkey key="k" command="TOOLMODE" value="MASSFRAG" description="Activates the Mass Fragmentation Tool"/>
			<Hotkey key="K" command="TOOLMODE" value="QUERY" description="Activates the Query Tool"/>

			<Hotkey key="=" command="DIALOG" value="CHOOSENICKNAME" description="Display a dialog to choose a Nickname"/>
			<Hotkey key="/" command="DIALOG" value="PROPERTIES" description="Displays the Properties Dialog"/>
			<Hotkey key="?" command="DIALOG" value="PROPERTIES" description="Displays the Properties Dialog"/>


		</Hotkeys>

	</Object>


	<Object type="AA1">

		<Commands>

			<Command id="AA1" description="Sets the Label for the single letter Amino Acids"/>

		</Commands>

		<Hotkeys>
			<Hotkey key="a" command="AA1" value="A" description="Ala"/>
			<Hotkey key="r" command="AA1" value="R" description="Arg"/>
			<Hotkey key="n" command="AA1" value="N" description="Asn"/>
			<Hotkey key="d" command="AA1" value="D" description="Asp"/>
